server {
    listen 80;
    server_name localhost;

    error_page 404 =302 /error.html?code=404&message=Pagina%20no%20encontrada;
    error_page 500 502 503 504 =302 /error.html?code=500&message=Error%20interno%20del%20servidor;

    location / {
        root /var/www/html;
        index index.html login.html;
        try_files $uri $uri/ /index.html;
    }

    # Desactivar caché para archivos CSS y JS (Cache-Busting)
    location ~* \.(css|js)$ {
        root /var/www/html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires -1;
        try_files $uri =404;
    }

    location /api {
        proxy_pass http://host.docker.internal:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
