server {
    listen 80;
    server_name localhost;

    # El root principal de NGINX es el frontend montado en /var/www/html
    root /var/www/html;
    index index.html index.htm;

    charset utf-8;

    # Cualquier ruta que no sea /api carga el index.html del frontend
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Desactivar la caché persistente para archivos HTML para cache-busting automático
    location ~* \.html$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires -1;
        try_files $uri =404;
    }

    # Las rutas que comiencen con /api se procesan a través de PHP-FPM (Laravel)
    location /api {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        # Necesitamos pasar el REQUEST_URI correctamente a Laravel
        fastcgi_param REQUEST_URI $request_uri;
        include fastcgi_params;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
