name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH deployment commands
        uses: appleboy/ssh-action@7eaf76671a0d7e532651b75b4d493a1cfd077e6e # v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/proyectoDesweb
            git reset --hard
            git pull origin main
            chown -R www-data:www-data /var/www/proyectoDesweb
            cd /var/www/proyectoDesweb/backend
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
